version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "13007:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mern-backend
    ports:
      - "13006:5000"
    env_file:
      - .env.production
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/mern-auth?authSource=admin
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mern-frontend:latest
    container_name: mern-frontend
    ports:
      - "13005:80"
    depends_on:
      - backend

volumes:
  mongo-data:
